branch-defaults:
  authorization:
    environment: iro176BucketMapper-dev
    group_suffix: null
environment-defaults:
  iro176BucketMapper-dev:
    branch: null
    repository: null
global:
  application_name: iro176-bucket-mapper-api
  branch: null
  default_ec2_keyname: iro176BucketMapper-dev
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
